import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { commandsToRegister } from "../src/commands/registry.js";
import type { CommandDeps } from "../src/types/yargs.js";

type OptionConfig = Readonly<{
  type?: string;
  alias?: string | ReadonlyArray<string>;
  describe?: string;
  default?: unknown;
  demandOption?: boolean;
  choices?: ReadonlyArray<string>;
  array?: boolean;
  hidden?: boolean;
}>;

type RecordedOption = Readonly<{ name: string; config: OptionConfig }>;

type RecordedCommand = Readonly<{
  command: string;
  describe: string;
  positionals: RecordedOption[];
  options: RecordedOption[];
  examples: Array<readonly [command: string, description: string]>;
  children: RecordedCommand[];
}>;

type CommandModuleLike = Readonly<{
  command: string;
  describe: string;
  builder?: unknown;
}>;

const scriptName = "kontent";
// Both keyed by the top-level command segment. A command can have a colocated
// README without appearing in the root README's command index, and vice versa.
const commandsWithoutPage: ReadonlySet<string> = new Set([]);
const commandsWithoutIndexEntry: ReadonlySet<string> = new Set(["telemetry"]);
const commandsRoot = "src/commands";
const readmeTableStart = "<!-- commands:start -->";
const readmeTableEnd = "<!-- commands:end -->";
const referenceStart = "<!-- reference:start -->";
const referenceEnd = "<!-- reference:end -->";
const editHint =
  "<!-- The section between the reference markers is generated by `pnpm docs:generate` from the yargs definitions; edit those, not the section. Prose outside the markers is handwritten and yours to edit. -->";

const createRecordedCommand = (command: string, describe: string): RecordedCommand => ({
  command,
  describe,
  positionals: [],
  options: [],
  examples: [],
  children: [],
});

// Stands in for the yargs Argv the registrations expect: known calls are recorded,
// everything else is a chainable no-op. Handlers never run, so deps stay untouched.
const createBuilderRecorder = (target: RecordedCommand): unknown => {
  const handlers: Record<string, (...args: ReadonlyArray<unknown>) => void> = {
    command: (module) => {
      target.children.push(recordModule(module as CommandModuleLike));
    },
    positional: (name, config) => {
      target.positionals.push({ name: name as string, config: config as OptionConfig });
    },
    option: (name, config) => {
      target.options.push({ name: name as string, config: config as OptionConfig });
    },
    example: (command, description) => {
      target.examples.push([command as string, description as string]);
    },
  };

  const recorder: unknown = new Proxy(
    {},
    {
      get:
        (_, property: string) =>
        (...args: ReadonlyArray<unknown>) => {
          handlers[property]?.(...args);
          return recorder;
        },
    },
  );
  return recorder;
};

const recordModule = (module: CommandModuleLike): RecordedCommand => {
  const recorded = createRecordedCommand(module.command, module.describe);
  if (typeof module.builder === "function") {
    module.builder(createBuilderRecorder(recorded));
  }
  return recorded;
};

const recordCommandTree = (): ReadonlyArray<RecordedCommand> => {
  const root = createRecordedCommand("", "");
  const recorder = createBuilderRecorder(root);
  const stubDeps = { telemetry: null } as unknown as CommandDeps;
  for (const register of commandsToRegister) {
    register(recorder as never, stubDeps);
  }
  return root.children;
};

// "$0 <endpoint>" is a default subcommand: it extends the parent path instead of
// adding a segment of its own.
const joinPath = (parentPath: string, command: string): string =>
  command.startsWith("$0")
    ? `${parentPath}${command.slice("$0".length)}`
    : `${parentPath} ${command}`;

const commandName = (node: RecordedCommand): string => node.command.split(" ")[0] ?? node.command;

const escapeTableCell = (text: string): string => text.replaceAll("|", "\\|");

const formatOptionNames = (option: RecordedOption): string => {
  const aliases =
    option.config.alias === undefined
      ? []
      : [option.config.alias]
          .flat()
          .map((alias) => (alias.length === 1 ? `-${alias}` : `--${alias}`));
  return [`--${option.name}`, ...aliases].map((name) => `\`${name}\``).join(", ");
};

const formatOptionType = (option: RecordedOption): string => {
  if (option.config.choices !== undefined) {
    return option.config.choices.map((choice) => `\`${choice}\``).join(" \\| ");
  }
  const baseType = option.config.type ?? "string";
  return option.config.array === true ? `${baseType}[]` : baseType;
};

const formatOptionDescription = (option: RecordedOption): string => {
  const requiredPrefix = option.config.demandOption === true ? "**Required.** " : "";
  const describe = option.config.describe ?? "";
  const hasDefault = option.config.default !== undefined && option.config.default !== false;
  const separator = describe === "" || describe.endsWith(".") ? "" : ".";
  const defaultSuffix = hasDefault
    ? `${separator} Default: \`${String(option.config.default)}\`.`
    : "";
  return `${requiredPrefix}${describe}${defaultSuffix}`;
};

const renderOptionsTable = (options: ReadonlyArray<RecordedOption>): ReadonlyArray<string> => [
  "| Option | Type | Description |",
  "| --- | --- | --- |",
  ...options.map(
    (option) =>
      `| ${formatOptionNames(option)} | ${formatOptionType(option)} | ${escapeTableCell(formatOptionDescription(option))} |`,
  ),
];

const renderArgumentsTable = (
  positionals: ReadonlyArray<RecordedOption>,
): ReadonlyArray<string> => [
  "| Argument | Type | Description |",
  "| --- | --- | --- |",
  ...positionals.map(
    (positional) =>
      `| \`<${positional.name}>\` | ${positional.config.type ?? "string"} | ${escapeTableCell(positional.config.describe ?? "")} |`,
  ),
];

const renderExamples = (
  examples: ReadonlyArray<readonly [string, string]>,
): ReadonlyArray<string> => [
  "```sh",
  ...examples.flatMap(([command, description], index) => [
    ...(index === 0 ? [] : [""]),
    `# ${description}`,
    command.replaceAll("$0", scriptName),
  ]),
  "```",
];

// A runnable leaf; groups only contribute path segments and directory levels.
type LeafDoc = Readonly<{
  path: string;
  fileSegments: ReadonlyArray<string>;
  node: RecordedCommand;
}>;

const collectLeaves = (
  node: RecordedCommand,
  parentPath: string,
  parentSegments: ReadonlyArray<string>,
): ReadonlyArray<LeafDoc> => {
  const path = joinPath(parentPath, node.command);
  // A "$0" default subcommand keeps the parent's identity (e.g. the mapi folder).
  const segments = node.command.startsWith("$0")
    ? parentSegments
    : [...parentSegments, commandName(node)];
  if (node.children.length > 0) {
    return node.children.flatMap((child) => collectLeaves(child, path, segments));
  }
  return [{ path, fileSegments: segments, node }];
};

const hasPage = (leaf: LeafDoc): boolean => !commandsWithoutPage.has(leaf.fileSegments[0] ?? "");

const hasIndexEntry = (leaf: LeafDoc): boolean =>
  !commandsWithoutIndexEntry.has(leaf.fileSegments[0] ?? "");

// A top-level command's module lives in a folder of its own name; a nested leaf's
// module lives in its parent group's folder (e.g. project/sample/bootstrap.ts).
const leafFolderSegments = (leaf: LeafDoc): ReadonlyArray<string> =>
  leaf.fileSegments.length === 1 ? leaf.fileSegments : leaf.fileSegments.slice(0, -1);

const leafReadmePath = (leaf: LeafDoc): string =>
  join(commandsRoot, ...leafFolderSegments(leaf), "README.md");

const groupLeavesByReadme = (
  leaves: ReadonlyArray<LeafDoc>,
): ReadonlyMap<string, ReadonlyArray<LeafDoc>> =>
  leaves.reduce((groups, leaf) => {
    const path = leafReadmePath(leaf);
    return new Map(groups).set(path, [...(groups.get(path) ?? []), leaf]);
  }, new Map<string, ReadonlyArray<LeafDoc>>());

const renderLeafSections = (leaf: LeafDoc, headingLevel: number): ReadonlyArray<string> => {
  const heading = "#".repeat(headingLevel);
  const visibleOptions = leaf.node.options.filter((option) => option.config.hidden !== true);
  return [
    `${heading} Usage`,
    "",
    "```sh",
    `${leaf.path}${visibleOptions.length > 0 ? " [options]" : ""}`,
    "```",
    "",
    ...(leaf.node.positionals.length > 0
      ? [`${heading} Arguments`, "", ...renderArgumentsTable(leaf.node.positionals), ""]
      : []),
    ...(visibleOptions.length > 0
      ? [`${heading} Options`, "", ...renderOptionsTable(visibleOptions), ""]
      : []),
    ...(leaf.node.examples.length > 0
      ? [`${heading} Examples`, "", ...renderExamples(leaf.node.examples), ""]
      : []),
  ];
};

const renderReferenceBlock = (leaves: ReadonlyArray<LeafDoc>): string => {
  const lines =
    leaves.length === 1 && leaves[0] !== undefined
      ? [leaves[0].node.describe, "", ...renderLeafSections(leaves[0], 2)]
      : leaves.flatMap((leaf) => [
          `## \`${leaf.path}\``,
          "",
          leaf.node.describe,
          "",
          ...renderLeafSections(leaf, 3),
        ]);
  return lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/\n+$/, "");
};

const spliceBetween = (
  content: string,
  start: string,
  end: string,
  replacement: string,
): string | null => {
  const startIndex = content.indexOf(start);
  const endIndex = content.indexOf(end);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return null;
  }
  const before = content.slice(0, startIndex + start.length);
  const after = content.slice(endIndex);
  return `${before}\n${replacement}\n${after}`;
};

const renderSkeleton = (leaves: ReadonlyArray<LeafDoc>, block: string): string => {
  const title =
    leaves.length === 1 && leaves[0] !== undefined
      ? leaves[0].path
      : `${scriptName} ${leafFolderSegments(leaves[0] as LeafDoc).join(" ")}`;
  return [`# \`${title}\``, "", editHint, "", referenceStart, block, referenceEnd, ""].join("\n");
};

const fileExists = async (path: string): Promise<boolean> =>
  stat(path).then(
    () => true,
    () => false,
  );

const updateCommandReadme = async (
  absolutePath: string,
  leaves: ReadonlyArray<LeafDoc>,
): Promise<void> => {
  const block = renderReferenceBlock(leaves);
  if (!(await fileExists(absolutePath))) {
    await writeFile(absolutePath, renderSkeleton(leaves, block));
    return;
  }
  const content = await readFile(absolutePath, "utf8");
  const spliced = spliceBetween(content, referenceStart, referenceEnd, block);
  if (spliced === null) {
    throw new Error(
      `${absolutePath} exists but is missing the ${referenceStart} / ${referenceEnd} markers. Add them where the generated reference belongs.`,
    );
  }
  if (spliced !== content) {
    await writeFile(absolutePath, spliced);
  }
};

const findStaleReadmes = async (
  root: string,
  expectedPaths: ReadonlySet<string>,
): Promise<ReadonlyArray<string>> => {
  const entries = await readdir(join(root, commandsRoot), { recursive: true });
  const readmePaths = entries
    .filter((entry) => entry === "README.md" || entry.endsWith(`${sep}README.md`))
    .map((entry) => join(commandsRoot, entry));
  const stale: string[] = [];
  for (const path of readmePaths) {
    if (expectedPaths.has(path)) {
      continue;
    }
    const content = await readFile(join(root, path), "utf8");
    if (content.includes(referenceStart)) {
      stale.push(path);
    }
  }
  return stale;
};

const renderReadmeTable = (leaves: ReadonlyArray<LeafDoc>): string => {
  const rows = leaves.filter(hasIndexEntry).map((leaf) => {
    const label = `\`${leaf.path}\``;
    const nameCell = hasPage(leaf) ? `[${label}](${leafReadmePath(leaf)})` : label;
    return `| ${nameCell} | ${escapeTableCell(leaf.node.describe)} |`;
  });
  return ["| Command | Description |", "| --- | --- |", ...rows].join("\n");
};

const repoRoot = fileURLToPath(new URL("..", import.meta.url));

const leaves = recordCommandTree().flatMap((node) => collectLeaves(node, scriptName, []));
const readmeGroups = groupLeavesByReadme(leaves.filter(hasPage));

for (const [path, group] of readmeGroups) {
  const folder = join(repoRoot, path, "..");
  if (!(await fileExists(folder))) {
    throw new Error(
      `Expected command folder ${relative(repoRoot, folder)} does not exist. Command folders must be named after their command path segments.`,
    );
  }
  await updateCommandReadme(join(repoRoot, path), group);
}

// Deleting or renaming a command must not leave its old page behind unnoticed; pages
// hold handwritten prose, so flag them for a human instead of deleting.
const stalePaths = await findStaleReadmes(repoRoot, new Set(readmeGroups.keys()));
if (stalePaths.length > 0) {
  throw new Error(
    `Stale command README(s) with no matching command: ${stalePaths.join(", ")}. Move their handwritten content or delete them.`,
  );
}

const rootReadmePath = join(repoRoot, "README.md");
const rootReadme = await readFile(rootReadmePath, "utf8");
const splicedRoot = spliceBetween(
  rootReadme,
  readmeTableStart,
  readmeTableEnd,
  renderReadmeTable(leaves),
);
if (splicedRoot === null) {
  throw new Error(`README.md is missing the ${readmeTableStart} / ${readmeTableEnd} markers.`);
}
if (splicedRoot !== rootReadme) {
  await writeFile(rootReadmePath, splicedRoot);
}

console.error(`Updated ${readmeGroups.size} command README(s) and the root README table.`);
