name: Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - run: npm i
    - run: npm run lint
    - run: npm run build
    - run: npm run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
